name: 更新下载

on:
  release:
    types: [published]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment variables
        id: setvars
        run: |
          # 提取纯数字版本号 (移除 'v' 和点号)
          CLEAN_VERSION=$(echo ${{ github.event.release.tag_name }} | tr -d 'v.' | sed 's/^0*//')
          
          # 确保版本号是数字
          if ! [[ "$CLEAN_VERSION" =~ ^[0-9]+$ ]]; then
            echo "Error: Version code must be a number"
            exit 1
          fi
          
          # 设置输出变量
          echo "VERSION_CODE=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Find release asset URL
        id: findasset
        run: |
          # 查找第一个 zip 格式的发布资源
          ZIP_URL=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }} \
            | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url' | head -1)

          if [ -z "$ZIP_URL" ]; then
            echo "Error: No zip asset found in release"
            exit 1
          fi

          # 添加代理前缀
          PROXIED_URL="https://v6.gh-proxy.com/$ZIP_URL"
          echo "ZIP_URL=$PROXIED_URL" >> $GITHUB_ENV

      - name: Update update.json
        run: |
          # 创建新的 JSON 内容
          JSON_CONTENT=$(jq -n \
            --arg version "$NEW_VERSION" \
            --arg versionCode "$VERSION_CODE" \
            --arg zipUrl "$ZIP_URL" \
            --arg changelog "https://raw.githubusercontent.com/${{ github.repository }}/main/updatelog.md" \
            '{version: $version, versionCode: $versionCode, zipUrl: $zipUrl, changelog: $changelog}')

          # 写入文件
          echo "$JSON_CONTENT" > update.json

      - name: Commit and push changes to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 确保在 main 分支
          git checkout main

          # 拉取最新更改，使用 merge 而不是 rebase 以避免冲突
          git pull origin main

          git add update.json

          # 如果没有暂存的改动则跳过提交
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update version to $NEW_VERSION"

          # 直接推送，因为我们已经拉取了最新更改
          git push origin main
